### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by IIAIronWolf** [JoshuaMulliken/ha-wyzeapi#82] opened 2020-09-10 21:26 UTC
**Describe the bug**

After failing multiple times to setup the HomeKit integration, I believe the issue was being caused by the wyzeapi, due to the associated errors in my logs, which occurred everytime I tried to setup HomeKit.
The weird part is, however, that I no longer have the ha-wyzeapi integration installed. In fact, I haven't had it installed in a long time. There is not reference to this integration in my configuration.yaml, the repo has been removed from custom repositories in HACS, and I can't find anything in reference to this integration anywhere within my file system or logs (besides the one that causes HomeKit setup to fail).
Luckily, HomeKit is working on a bugfix to stop any missing integrations from failing the HomeKit startup. However, I think this is something that needs to be addressed by ha-wyzeapi as well, as I had deleted this integration and my system is still referencing it, making me think it is still hidden there somewhere.

**To Reproduce**
1. Go to 'Configuration -> Integrations -> search for HomeKit Bridge and install | Or setup through configuration.yaml'
2. Go to logs. May need to refresh.
3. See error referencing the Wyzeapi at the end of the HomeKit Bridge setup.

**System configuration**
System: HassOS 4.13
HA Version:  0.114.4
WyzeApi Version:  Uninstalled...

**configuration.yaml**

```yaml
<Not using a config for this integration. Uninstalled it.>
```

**home-assistant.log**

```
2020-09-10 14:55:18 DEBUG (MainThread) [homeassistant.components.homekit] Begin setup HomeKit for HASS Bridge XHBX
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: Name to HASS Bridge XHBX
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: SerialNumber to default
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: FirmwareRevision to 0.114.4
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: Manufacturer to Home Assistant
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: Model to Bridge
2020-09-10 14:55:18 DEBUG (SyncWorker_6) [pyhap.characteristic] set_value: SerialNumber to homekit.bridge
2020-09-10 14:55:18 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry HASS Bridge XHBX:51828 for homekit
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 242, in async_setup_entry
    await homekit.async_start()
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 505, in async_start
    await self._async_set_device_info_attributes(
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 668, in _async_set_device_info_attributes
    integration = await async_get_integration(self.hass, ent_reg_ent.platform)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 454, in async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'wyzeapi' not found.

```

**Comment by IIAIronWolf** [comment] 2020-09-11 16:35
Fixed my particular issue in: https://github.com/home-assistant/core/pull/39918

However, please update this integration to fully remove itself and all its traces when uninstalling via the HACS Integrations page.

**Comment by JoshuaMulliken** [comment] 2020-09-12 04:35
As it appears this is not a bug with this integration I am closing

**Closed** 2020-09-12 04:35 UTC
Labels: invalid

**Comment by IIAIronWolf** [comment] 2020-09-12 14:54
The bug is with wyzeapi @JoshuaMulliken ...
If my home assistant server is to calling out wyzeapi errors and I haven't had that integration installed for months, then something is wrong. I uninstalled it using the HACS integration page long before ever trying to install HomeKit. Why would it still be saying it can't find wyzeapi?

Also, per HomeAssistant/core rules, I cannot create an issue because this is an unofficial integration.

**Comment by JoshuaMulliken** [comment] 2020-09-12 14:55
From my perspective it is a HACS issue because integrations do not handle there own uninstallation.

**Comment by JoshuaMulliken** [comment] 2020-09-12 14:57
I can use HomeKit with this integration just fine. Please file with HACS or manually attempt to delete the files from the custom_components directory

**Comment by IIAIronWolf** [comment] 2020-09-12 14:57
Why would my other uninstalled integrations _not_ show up in the HomeKit installation failure logs then? 
Suppose I'll have to talk to HACS...

**Comment by IIAIronWolf** [comment] 2020-09-12 14:59
Well if I had it installed, it would work fine. However, I don't have it, which is the problem outlined here. 
This has been fixed by the HomeKit dev, thankfully. Missing integrations not longer cause HomeKit setup to fail.
And there is no trace of this integration in my custom_components or anywhere else that I could find in the file system. 
Opening yet another issue with HACS.
