### ISSUE TITLE
[Feature Request] Set switches as devices

### ISSUE THREAD

**Issue by AkshatShah1** [JoshuaMulliken/ha-wyzeapi#59] opened 2020-06-04 18:11 UTC
**Is your feature request related to a problem? Please describe.**
Kind of, due to the fact that the switches are only entities ATM, I cannot setup an automation with them

**Describe the solution you'd like**
I would like the switches to be added as devices so it is possible and more streamlined to create automations and such

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AkshatShah1** [comment] 2020-06-04 19:43
Yes I can do that, however, I cannot set it as an action. LIke for example if I want to turn my lights off at sunset I can make it so that the automation only proceeds if the wyze switch is on/off but I can't make it so that sunset turns off the switch

**Comment by imhotep** [comment] 2020-06-07 02:02
@AkshatShah1 define an action "Call service" and specify switch.on/off/toggle and select the entity?

**Comment by AkshatShah1** [comment] 2020-06-07 02:24
That's why I labeled this as a feature request instead of a bug. It's possible but it would be better for them to be listed as devices instead of entities

**Comment by AkshatShah1** [comment] 2020-06-07 02:34
I can, but it would be more streamlined and "proper" for it to be labeled as a device. It isn't a big issue, that's why I labeled this as a feature request instead of a bug.

**Comment by AkshatShah1** [comment] 2020-06-07 04:40
I can, but it would be more streamlined and "proper" for it to be labeled as a device. It isn't a big issue, that's why I labeled this as a feature request instead of a bug.

**Comment by jfarmer08** [comment] 2020-06-09 00:31
I will close this Request in favor of the below. 
[Duplicate of #56](https://github.com/JoshuaMulliken/ha-wyzeapi/issues/56)

**Closed by jfarmer08** 2020-06-09 00:31 UTC
