### ISSUE TITLE
Add support for Wyze Switch (Feature Request)

### ISSUE THREAD

**Issue by wardend01** [JoshuaMulliken/ha-wyzeapi#360] opened 2022-03-16 19:47 UTC
Would be nice to have support for the wyze switch.  https://www.wyze.com/products/wyze-light-switch?_pos=1&_psq=Switch&_ss=e&_v=1.0

**Comment by Adam-North** [comment] 2022-03-25 18:08
I believe this is a duplicate of #296

**Closed** 2022-03-26 17:10 UTC
Labels: duplicate
