### ISSUE TITLE
Wyze Lock State attribute changes not being picked up

### ISSUE THREAD

**Issue by FrankJaco** [JoshuaMulliken/ha-wyzeapi#326] opened 2022-01-14 12:59 UTC
The Wyze lock has a sensor that detects if the door is open or closed. In Home Assistant, I believe this should be reflected by the door_open attribute going from false to true.However in HA it doesn't  change. It remains at false even when the door is open. Yet the Wyze software itself is fully aware when the door opens and will immediately push a notification.  

The following automation yaml never triggers even though the door is open.
...
  alias: test
  description: ''
  trigger:
  - platform: state
    entity_id: lock.garage_entry
    attribute: door_open
    for:
      hours: 0
      minutes: 0
      seconds: 3
    from: 'false'
  condition: []
  action:
  - service: notify.mobile_app_sm_xxxxx
    data:
      message: Door open attribute has changed from false for 3 sec.
  mode: single

**Comment by yoinx** [comment] 2022-02-09 20:53
@FrankJaco sorry for the incredibly delayed reply. I have been busy with life. However I'm looking at getting back into this project in the near future.

One of the issues I was having trying to implement the battery statuses is that it uses a different endpoint. On that endpoint, wyze's data seemed a bit confusing. So, I used the values that appeared to match what my door/lock was doing. It's entirely possible that I  missed up a value in the process. 

However, that being said... I'd like to hear if other users are experiencing this before dedicating too much time into it. Since I'm not sure that I'll be able replicate it (like I said, the values worked on my one lock).

I will say that you also have to keep in mind that we only poll the lock once every 15 seconds (which can go into a backoff to make that time even longer if you have a lot of devices). So you could potentially be hitting a point where the door is opened/closed off cycle and your data is delayed being displayed.

**Comment by LordNex** [comment] 2022-02-09 22:45
I can get an accurate battery level from the lock but the keypad always shows 100% and the lock still shows unavailable as it always does. Still functions via Zigbee though.


On Feb 9, 2022, at 2:54 PM, Joe Schubert ***@***.***> wrote:

﻿

@FrankJaco<https://github.com/FrankJaco> sorry for the incredibly delayed reply. I have been busy with life. However I'm looking at getting back into this project in the near future.

One of the issues I was having trying to implement the battery statuses is that it uses a different endpoint. On that endpoint, wyze's data seemed a bit confusing. So, I used the values that appeared to match what my door/lock was doing. It's entirely possible that I missed up a value in the process.

However, that being said... I'd like to hear if other users are experiencing this before dedicating too much time into it. Since I'm not sure that I'll be able replicate it (like I said, the values worked on my one lock).

I will say that you also have to keep in mind that we only poll the lock once every 15 seconds (which can go into a backoff to make that time even longer if you have a lot of devices). So you could potentially be hitting a point where the door is opened/closed off cycle and your data is delayed being displayed.

**Comment by FrankJaco** [comment] 2022-02-10 16:38
I was able to expose that door open attribute by templating a binary 
sensor instead of directly trying to trigger off of the lock's 
attribute. As thus was not too much work, I don't see a need for you to 
dedicate excessive time into it.

binary_sensor:
   - platform: template
     sensors:
      garage_entry_open:
         friendly_name: "Garage Entry Open"
         value_template: "{{ state_attr('lock.garage_entry','door_open')}}"


fj

**Comment by yoinx** [comment] 2022-02-10 21:39
> I was able to expose that door open attribute by templating a binary sensor instead of directly trying to trigger off of the lock's attribute. As thus was not too much work, I don't see a need for you to dedicate excessive time into it. binary_sensor:   - platform: template     sensors:      garage_entry_open:         friendly_name: "Garage Entry Open"         value_template: "{{ state_attr('lock.garage_entry','door_open')}}" fj

Sorry, I'm less of a home assistant expert than you may think... 

I would think that this works as intended then? The value in the properties that is being provided is basically just a boolean, there is no binary sensory attached to it in the integration (all binary sensors were removed)... so it seems like it would make sense that you'd have to template your own binary sensor for it. At least in my limited understanding of how Home Assistant works.

If that's the case, I'm going to go ahead and close this.

**Closed** 2022-02-11 20:09 UTC
Labels: bug
