### ISSUE TITLE
Add support for Wyze V2 door and motion sensors

### ISSUE THREAD

**Issue by rugene76** [JoshuaMulliken/ha-wyzeapi#174] opened 2021-05-20 19:46 UTC
Thanks so much for the fantastic work on the wyzeapi! :-)
Now that the wyze sense v1 is behind us, it would be great to add support for wyze sense V2. 

I do make extensive use of the lock support but I also have doors and windows that I use the v2 sense and motion detector on.

I'd be happy to test the code as I have several v2 sensors installed and more on the way. Apparently they can be connected to the v1 as well as the new v2 bridge so I could test the code under various conditions.

Much appreciated!

**Comment by JoshuaMulliken** [comment] 2021-05-22 02:53
duplicate of #140

**Closed by JoshuaMulliken** 2021-05-22 02:53 UTC
Labels: Feature Request
