### ISSUE TITLE
[Bug] Wyze Switch status not updating

### ISSUE THREAD

**Issue by joseabelsalcedo** [JoshuaMulliken/ha-wyzeapi#72] opened 2020-08-13 14:19 UTC
When the status of a Wyze Switch is changed using the Wyze App (or any other external source to HA) the entity's state is not updated. If the state is changed using Lovelace the update is immediate.

**To Reproduce**
1. Open a Lovelace's dashboard in which there is a button or entity of the switch.
2. With the component's log set to DEBUG, change the status of the switch using Wyze App.
3. See in the logs that there is an update of the entity. 
4. Confirm that the state doesn't change even after two updates of the api.

**Expected behavior**
The state of the entity to be updated. 

**System configuration**
System: Docker
HA Version: v0.113.3
WyzeApi Version: v0.5.0

**configuration.yaml**

logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug

wyzeapi:
  username: !secret wyze_user
  password: !secret wyze_pass

```

**home-assistant.log**

I'll attach two log files, one with updates from the Wyze app and another updating the switch from Home Assistant.

[wyze.log](https://github.com/JoshuaMulliken/ha-wyzeapi/files/5069547/wyze.log)
[wyze_change_from_HA.log](https://github.com/JoshuaMulliken/ha-wyzeapi/files/5069548/wyze_change_from_HA.log)

```

```

**Comment by JoshuaMulliken** [comment] 2020-08-13 22:04
Yes since this is a cloud integration the status will not be immediately updated if it is changed outside of home assistant. If you wait it will figure it out but it will not know immediately.

This is a known problem with integrations that do cloud pull.

**Comment by uzegonemad** [comment] 2020-08-18 18:32
@JoshuaMulliken I'm experiencing this issue as well.

I tried two scenarios:
1. Turn on via Alexa voice command
2. Turn on via Wyze app

In both scenarios, I waited over 20 minutes and the status didn't update inside Home Assistant.

The status did change after I restarted HA.

All of my wyze sensors & bulbs update within a reasonable amount of time. Is it possible that switch status isn't polling correctly?

**Comment by JoshuaMulliken** [comment] 2020-08-18 20:17
@uzegonemad I can check it out

**Comment by JoshuaMulliken** [comment] 2020-08-23 19:53
@uzegonemad I did not see anything different from how the others are working. I am not sure what is happening in your case. I do not have a switch so I cannot do any tests.

**Comment by joseabelsalcedo** [comment] 2020-08-23 20:18
Hey @JoshuaMulliken  since you can't do tests without a switch, let me know if you think of something that one of us can test. I understand the Cloud Polling behavior but the thing is that unlike the light and sensors the status of the switch is not updated after the polling time.

**Comment by JoshuaMulliken** [comment] 2020-08-23 21:50
@joseabelsalcedo, @uzegonemad Actually I think I found an issue with the switch integration!

I am going to publish a beta in a few minutes so if ya'll could try that out then let me know

**Comment by joseabelsalcedo** [comment] 2020-08-25 00:46
> @joseabelsalcedo, @uzegonemad Actually I think I found an issue with the switch integration!
> 
> I am going to publish a beta in a few minutes so if ya'll could try that out then let me know

Hi, so I tried to install the latest beta ( version v0.5.1-beta.1 ) but it gives an error:

`2020-08-24 20:33:27 ERROR (MainThread) [homeassistant.setup] Setup failed for wyzeapi: Unable to import component: cannot import name 'WyzeApi' from partially initialized module 'custom_components.wyzeapi.wyzeapi.wyzeapi' (most likely due to a circular import) (/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py)`

Checking the configuration i got this error (it wasn't present before the beta and is not appearing after the downgrade):
```
2020-08-24 20:37:27 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/core.py", line 29, in post
    errors = await async_check_ha_config_file(request.app["hass"])
  File "/usr/src/homeassistant/homeassistant/config.py", line 857, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 115, in async_check_ha_config_file
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    for dep in integration.dependencies + integration.after_dependencies
TypeError: unsupported operand type(s) for +: 'dict' and 'list'
```

so I had to revert to v0.5.0.

**Comment by jscherry** [comment] 2020-08-25 01:43
I also got the same error as above after updating to the most recent beta so I installed the regular version 5 and everything is working again. How do I get rid of the update message in HACS if I don't want to update to a beta? Error from beta was:ERROR (MainThread) [homeassistant.setup] Setup failed for wyzeapi: Unable to import component: cannot import name 'WyzeApi' from partially initialized module 'custom_components.wyzeapi.wyzeapi.wyzeapi' (most likely due to a circular import) (/config/custom_components/wyzeapi/wyzeapi/wyzeapi.py)

**Comment by JoshuaMulliken** [comment] 2020-08-25 19:26
@everyone I pulled that release. I'll try to get it up and working.

**Comment by JoshuaMulliken** [comment] 2020-08-26 00:10
@everyone beta 2 is now available. Hopefully this goes better 😭

**Comment by joseabelsalcedo** [comment] 2020-08-26 01:22
@JoshuaMulliken so far everything is working as expected, tomorrow I'll do some more tests. Top job!!

**Comment by joseabelsalcedo** [comment] 2020-08-28 15:36
Hi @JoshuaMulliken 

From my point of view the bug can be closed. After your last change the switch's status is refreshing as expected. Thanks for the fix.

**Comment by JoshuaMulliken** [comment] 2020-08-28 16:45
Great thank you!

**Comment by uzegonemad** [comment] 2020-08-30 01:08
@JoshuaMulliken I also wanted to confirm that this is now working as expected. Thank you so much for your work.

**Comment by erj11** [comment] 2021-12-02 04:43
@joseabelsalcedo It seems this issue may be back. Similar issue as described above (state not updating when the plug is turned off in the app but updates fine when done from inside HA). Any suggestions? Thanks

**Comment by erj11** [comment] 2021-12-02 21:08
@JoshuaMulliken thanks for the note and support. Looks like this is similar to the recent #297 issue.

**Comment by yoinx** [comment] 2021-12-04 19:10
This should be closed imo and tracked in #297 as this bug was related to home assistant's updates on the entities and the current bug is related to the update_manager logic in wyzeapy.

**Comment by JoshuaMulliken** [comment] 2021-12-08 16:22
@yoinx makes sense.

Closing in favor of #297

**Closed by JoshuaMulliken** 2021-12-08 16:22 UTC
Labels: bug

**Comment by santiago990513** [comment] 2022-09-24 20:41
The issue is back. Hi, I'm new to home assistant.
When I control the wyze bulbs color video the wyze app or the voice assistants the status won't update in HA.

**Comment by JoshuaMulliken** [comment] 2022-09-29 13:55
@santiago990513 they are blocking requests to update the status of the devices so it is not really something they can do
