### ISSUE TITLE
[Feature Request] Spotlight Add-on

### ISSUE THREAD

**Issue by MrAnonymous722** [JoshuaMulliken/ha-wyzeapi#159] opened 2021-05-07 02:20 UTC
The spotlight addition for the V3 (and maybe the V2?) is great, but will be even better once I can setup automations with it in HA. I hope we will see this in an update soon :)

**Comment by JoshuaMulliken** [comment] 2021-05-07 12:41
Duplicate of https://github.com/JoshuaMulliken/ha-wyzeapi/issues/123

**Closed by JoshuaMulliken** 2021-05-07 12:41 UTC
