### ISSUE TITLE
[Bug] Two-Step verification fail

### ISSUE THREAD

**Issue by iamwilliamdiaz** [JoshuaMulliken/ha-wyzeapi#222] opened 2021-07-18 06:32 UTC
**Describe the bug**
Failed to set up if Two-Step verification is enabled

**System configuration**
System: 
HA Version: 
WyzeApi Version: 

**home-assistant.log**

Logger: homeassistant.components.light
Source: custom_components/wyzeapi/light.py:49
Integration: Light (documentation, issues)
First occurred: 1:43:35 AM (2 occurrences)
Last logged: 2:20:48 AM

Error while setting up wyzeapi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/wyzeapi/light.py", line 49, in async_setup_entry
    lights = [WyzeLight(bulb_service, light) for light in await bulb_service.get_bulbs()]
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/services/bulb_service.py", line 81, in get_bulbs
    self._devices = await self.get_object_list()
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/services/base_service.py", line 92, in get_object_list
    check_for_errors_standard(response_json)
  File "/usr/local/lib/python3.8/site-packages/wyzeapy/utils.py", line 22, in check_for_errors_standard
    raise ParameterError(response_json)
wyzeapy.exceptions.ParameterError: {'ts': 1626587015351, 'code': '1001', 'msg': 'ParameterError', 'data': {}}

**Comment by JoshuaMulliken** [comment] 2021-07-27 17:53
dupe of #39

**Closed by JoshuaMulliken** 2021-07-27 17:53 UTC
Labels: bug
