### ISSUE TITLE
Color Bulbs: "Failed to connect to bulb"

### ISSUE THREAD

**Issue by tggman** [JoshuaMulliken/ha-wyzeapi#315] opened 2021-12-20 15:03 UTC
**Describe the bug**
Unable to control (e.g. power on/off) my Wyze Color Bulbs. Issue began when local loop/local control was added to the WyzeAPI

**To Reproduce**
1. Toggle the power on one of the offending bulbs. 
2. Bulb fails to respond 
3. Wait a few seconds and observe how the power slider for the bulb toggles back to it's previous state

Notes:
1. Issue seems to occur randomly on different bulbs, but once the problem occurs on a given bulb, it remains unresponsive. 
2. Power cycling the bulbs coupled with a HA restart sometimes (but not always) fixes the issue.
3. Bulbs may work initially after a HA restart, but can fail function later - after its been up for a time
4. Bulbs function as expected in the Wyze app.

**Expected behavior**
Function as expected via automations/manual control.

**System configuration**
WyzeAPI v0.1.2

## System Health

version | core-2021.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | aarch64
timezone | America/Chicago

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.18.0
Stage | running
Available Repositories | 929
Installed Repositories | 2

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 113.9 GB
disk_used | 10.2 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Terminal & SSH (9.2.1), Let's Encrypt (4.12.0), Duck DNS (1.14.0), Z-Wave JS (0.1.50)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 13
mode | storage
</details>

**home-assistant.log**

[home-assistant.log](https://github.com/JoshuaMulliken/ha-wyzeapi/files/7746131/home-assistant.log)

**Comment by ItsRhen** [comment] 2021-12-21 03:37
Same happening here. I appreciate the work on this integration!

**Comment by jscherry** [comment] 2021-12-21 22:56
Color bulbs stopped connecting after light strip added. Light strip pro working well though. Josh i've been reading the info on github pull releases etc so I can help in the future.

**Comment by brg468** [comment] 2021-12-21 23:17
All color bulbs? Or the same intermittent behavior as described above? 

> Color bulbs stopped connecting after light strip added. Light strip pro working well though. Josh i've been reading the info on github pull releases etc so I can help in the future.

**Comment by tggman** [comment] 2021-12-21 23:18
Until this issue is resolved, can we please either disable the local loop feature (which I would love if it was reliable) or make it an option. May smart home is acting real dumb...

**Comment by djljr** [comment] 2021-12-22 03:13
I believe the cause of the color bulbs not working is this conditional here:
https://github.com/JoshuaMulliken/wyzeapy/pull/32/files#diff-68dc0b66d98ff1a4284e5dc7e17a632d16e7f4091b61dc966556ed11ecb868f5R83

The `and` has [higher precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence) than the `or` causing it to try and set values for the color property of the bulb that are not hex strings. This causes this error when it asserts the value *is* a hex string, at least for me:

```2021-12-21 21:52:07 ERROR (MainThread) [homeassistant.components.light] wyzeapi: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
await task
File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
await func(*args, **kwargs)
File "/config/custom_components/wyzeapi/light.py", line 232, in async_update
self._bulb = await self._bulb_service.update(self._bulb)
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 88, in update
bulb.color = value
File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 60, in color
assert re.match(r"^([A-Fa-f\d]{6}|[A-Fa-f\d]{3})$", value) is not None
AssertionError
```

**Comment by brg468** [comment] 2021-12-22 05:33
> I believe the cause of the color bulbs not working is this conditional here: https://github.com/JoshuaMulliken/wyzeapy/pull/32/files#diff-68dc0b66d98ff1a4284e5dc7e17a632d16e7f4091b61dc966556ed11ecb868f5R83
> 
> The `and` has [higher precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence) than the `or` causing it to try and set values for the color property of the bulb that are not hex strings. This causes this error when it asserts the value _is_ a hex string, at least for me:
> 
Yep, you are absolutely right. I screwed that one up. Will get a fix in tomorrow!

**Comment by brg468** [comment] 2021-12-22 16:07
New PR's submitted to correct the broken color bulbs. 

https://github.com/JoshuaMulliken/ha-wyzeapi/pull/316
https://github.com/JoshuaMulliken/wyzeapy/pull/33

**Comment by tggman** [comment] 2021-12-22 17:25
> New PR's submitted to correct the broken color bulbs.
> 
> #316 [JoshuaMulliken/wyzeapy#33](https://github.com/JoshuaMulliken/wyzeapy/pull/33)
> 
> I don't have any bulbs, which is how I missed this the first time. If anybody with bulbs wants to test this I would appreciate it.

Be glad to ... how do I get the updated/latest version?

**Comment by brg468** [comment] 2021-12-22 18:42
If you want you can download and replace the `wyzeapy` folder in `custom_components` from [here ](https://github.com/brg468/ha-wyzeapi/tree/fix-bulbs).

Then just drop the `wyzeapy` folder into your config folder from [here](https://github.com/brg468/wyzeapy/tree/fix-bulbs) (That will use the updated dependency).

That being said I think an update will be out soon.

**Comment by tggman** [comment] 2021-12-22 20:26
@brg468 for test purposes, can I simply replace lines 120-122 with the new code in lines 120-124 in the file lights.py?

**Comment by brg468** [comment] 2021-12-22 20:34
Unfortunately no, there was a similar error in `bulb_service.py` in the dependency (`wyzeapy`). They both need to be updated. If you can find `wyzeapy` you can update it as well, or dropping that folder into your config should have the same effect.

**Comment by tggman** [comment] 2021-12-22 20:51
I've looked for wyzeapi in the past (so as to avoid installing HACS) but gave up. Didn't know I could just drop it in the config folder. Thanks for the info. 

I don't mind doing this if it becomes necessary, but if it fails to correct the issues, there will still be questions. So at this point, lets just wait for the update to be pushed out and take it from there. Thanks again for your help and support.

**Comment by brg468** [comment] 2021-12-22 20:56
👍. And just to be clear, this won’t address the original issue of the bulbs intermittently stopping working, this is just to fix the issue with all color bulbs that was introduced with the light strip addition.

**Comment by tggman** [comment] 2021-12-22 21:00
That is exactly my concern. I myself didn't think it would solve the disconnect issue, but I thought that the consensus here.  Well that sucks.

I am really getting sick of Wyze on so many fronts. I have a ton of LIFX lights which cost 3x more but have an open API and work flawlessly.  Getting real close to biting the bullet and spending a bunch of money on LIFX. Anybody interested in 8 Wyze color bulbs? LOL

**Comment by tggman** [comment] 2021-12-22 21:21
> 👍. And just to be clear, this won’t address the original issue of the bulbs intermittently stopping working, this is just to fix the issue with all color bulbs that was introduced with the light strip addition.

@JoshuaMulliken would it make sense at this point to disable local control until we find an actual fix for the disconnect issue? Right now 5 out of my 8 bulbs fail to connect - even after a HA restart.

**Comment by brg468** [comment] 2021-12-22 21:47
@tggman  Just curious,..Are they unavailable in HA or uncontrollable? Also, if its still available, does the IP address for the bulb(s) shown in the attributes in HA still reflect the correct IP?

**Comment by tggman** [comment] 2021-12-22 22:03
As it stands now, they are unavailable - which seems to coincide with them not coming back after a HA restart. And when they are unavailable, the IP and MAC attributes are missing so I can't say.

When I first encountered the problem, they simply failed to respond as I described in this issue. At that time, I checked the MAC (and the IP but not as sure) and it was correct.

**Comment by brg468** [comment] 2021-12-22 22:08
Are you running the newest version (so far) that added the light strips? Any new warn/error messages on startup with them being unavailable?

**Comment by tggman** [comment] 2021-12-22 22:14
I'll restart in a sec, but here is what it looks like after its been running for 24hrs

Logger: homeassistant.helpers.service
Source: helpers/service.py:129
First occurred: December 21, 2021, 6:22:50 PM (542 occurrences)
Last logged: 4:08:47 PM

Unable to find referenced entities light.kitchen_microwave
Unable to find referenced entities light.kitchen_stove
Unable to find referenced entities light.kitchen_ceiling_1, light.kitchen_ceiling_2, light.kitchen_ceiling_3
Unable to find referenced entities light.basement_desk_lamp_2
Unable to find referenced entities light.laundry_1, light.laundry_2

**Comment by tggman** [comment] 2021-12-22 22:21
Here's the (warning level) errors on startup:

Logger: homeassistant.components.light
Source: custom_components/wyzeapi/light.py:232
Integration: Light (documentation, issues)
First occurred: 4:17:42 PM (8 occurrences)
Last logged: 4:17:43 PM

wyzeapi: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/light.py", line 232, in async_update
    self._bulb = await self._bulb_service.update(self._bulb)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 88, in update
    bulb.color = value
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 60, in color
    assert re.match(r"^([A-Fa-f\d]{6}|[A-Fa-f\d]{3})$", value) is not None
AssertionError

--------------------------

Logger: homeassistant.helpers.service
Source: helpers/service.py:129
First occurred: 4:17:49 PM (2 occurrences)
Last logged: 4:17:49 PM

Unable to find referenced entities light.family_room_tv_bookshelf  (this is the guy that I had to hard reset at one point)

**Comment by brg468** [comment] 2021-12-22 22:25
Ok that first error is what was introduced by my (poorly) added light strip addition. So for now that’s blocking anything from being added.

**Comment by tggman** [comment] 2021-12-22 22:28
> I believe the cause of the color bulbs not working is this conditional here: https://github.com/JoshuaMulliken/wyzeapy/pull/32/files#diff-68dc0b66d98ff1a4284e5dc7e17a632d16e7f4091b61dc966556ed11ecb868f5R83
> 
> The `and` has [higher precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence) than the `or` causing it to try and set values for the color property of the bulb that are not hex strings. This causes this error when it asserts the value _is_ a hex string, at least for me:
> 
> ```
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
> await entity.async_device_update(warning=False)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
> await task
> File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
> await func(*args, **kwargs)
> File "/config/custom_components/wyzeapi/light.py", line 232, in async_update
> self._bulb = await self._bulb_service.update(self._bulb)
> File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 88, in update
> bulb.color = value
> File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/bulb_service.py", line 60, in color
> assert re.match(r"^([A-Fa-f\d]{6}|[A-Fa-f\d]{3})$", value) is not None
> AssertionError
> ```

Yeah I noticed ... which is what gave me hope

**Comment by tggman** [comment] 2021-12-22 22:29
Question: Does wyzeapi use the MAC or IP?

**Comment by brg468** [comment] 2021-12-22 22:36
Mainly the MAC, but it looks like for local control it’s using the IP to send the command.

**Comment by tggman** [comment] 2021-12-22 22:39
Well at this point lets wait for the dust to settle and update push. I'm guessing things will improve but not be 100% but who knows.  Take care

**Comment by tggman** [comment] 2021-12-23 19:42
As it stands now, the resolution of issue #316 by @brg468 seems to have corrected this issue.  Once @JoshuaMulliken merges both ha-wyzeapi and wyzeapi into the master, I'll reupdate, test it for a few days and close this issue.

**Comment by JoshuaMulliken** [comment] 2021-12-24 19:51
@tggman It has been merged and released to master. I am away from my main machine so I cannot test super heavily. Thanks for all your help with getting this tested and working!

**Comment by tggman** [comment] 2021-12-24 20:56
No problem @JoshuaMulliken. Glad to help. 

Just updated to the master and so far so good. I'll wait a bit and close the issue if all remains well over the next couple days and to give those watching/participating in this issue a chance to sound off if they are still having any relevant issues.

**Comment by boomam** [comment] 2021-12-25 01:58
Just to add to this -  the latest update (0.1.4) has made the lights appear in HA again, however it does nothing.
I can see the state/s in HA if I go and make the change in the Wyze app, however tapping the lovelace card buttons to turn on/off, adjusting the brightness, etc. is broken. Does nothing.

**Comment by tggman** [comment] 2021-12-25 13:44
@boomam I'm guessing you tried this already but I'll ask anyhow. did you try electrical power cycling the bulbs (pull power/wait 5-10s/restore power), then restarting HA? I had to do a bunch of gymnastics to get my bulbs to work right after this fix. 

I also noticed that if the Wyze App and HA are initially out of sync, one can undo what the other does until they get back in sync.

**Comment by boomam** [comment] 2021-12-25 14:51
> @boomam I'm guessing you tried this already but I'll ask anyhow. did you try electrical power cycling the bulbs (pull power/wait 5-10s/restore power), then restarting HA? I had to do a bunch of gymnastics to get my bulbs to work right after this fix.
> 
> I also noticed that if the Wyze App and HA are initially out of sync, one can undo what the other does until they get back in sync.

Morning!
I will try that when i get home tomorrow and report back :-)

**Comment by djljr** [comment] 2021-12-26 15:08
Everything working well on my end after the fix, thanks @brg468 !

**Comment by boomam** [comment] 2021-12-26 19:55
Just re-tested after doing a power off of the bulbs, same issue.
The state shows in HA (on, off, what its colour is, etc.) but there is zero control.
Same errors as before - 
````
Logger: wyzeapy.services.base_service
Source: /usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py:613
First occurred: 24 December 2021, 20:48:19 (39 occurrences)
Last logged: 14:53:48
* Failed to connect to bulb XYZ
````

**Comment by boomam** [comment] 2021-12-27 00:31
To add, interestingly, blowing the config/addon/HACS integration out, and re-adding it, appears to make it work again.
Only issue I've noticed is that the grouping of lights for the kitchen (2x lights) doesn't work, despite the same names on the entities.

**Comment by tggman** [comment] 2022-01-13 18:02
At this point, I think it's best to re-open this issue since it seems to be different enough from issue #297 and is/may be specific to color bulbs and the local IP method only. 

**Opinion / Suggestion**:
Until this issue can be resolved and IMHO, it's time we go back to using the cloud method of controlling color lights instead of using the local IP. The local IP method just isn't working reliably enough (for me at least) and it seems like we are no closer to finding root cause let alone a fix.

**Comment by brg468** [comment] 2022-01-19 23:51
@tggman would you want to try this out and see if it works for you? In the limited amount of testing I did (I only have the light stirp and no bulbs but I was able to reproduce what seemed like the same error) it seemed to work. There will be a delay of a few seconds when a bulb no longer responds locally but after that it should flag as offline and send the rest of the commands to the cloud for that bulb. 🤞 Again put the `wyzeapy` folder in your config folder, nothing to change in `custom_components`.

https://github.com/brg468/wyzeapy/tree/cloud-fallback-test

**Comment by tggman** [comment] 2022-01-20 01:12
Sure I'll give it a shot! I'll Install it tomorrow. Be advised that it will take quite a bit of time (at least a week) to fully vet since this is a highly intermittent issue. Will this create a log entry each time it's forced to fall back to the cloud?

**Comment by brg468** [comment] 2022-01-20 01:54
It

**Comment by tggman** [comment] 2022-01-20 13:52
@brg468 it's Installed and running. I'll let you know ...

**Comment by kmoniker** [comment] 2022-01-21 02:24
Following this since I'm having the same problem. Hoping this fix works!

**Comment by JoshuaMulliken** [comment] 2022-01-21 02:52
@brg468 Great work! Can you submit a PR with your changes?

**Comment by brg468** [comment] 2022-01-21 16:26
@JoshuaMulliken I was gonna let @tggman test it for a day or 2 and assuming it’s working correctly I’ll be happy to submit the PR’s.

**Comment by tggman** [comment] 2022-01-21 18:19
@JoshuaMulliken its up and running on my install. the problem is this is a very intermittent issue and I can't force a local access error since we don't know root cause.

I'm not an expert on the release process, but if you're proposing it be released as a beta that would be good since it may take awhile for it to fail local access and revert to he cloud on a single install.

**Comment by brg468** [comment] 2022-01-21 18:48
> will wyzeapy gracefully handle a total network connection fail (no local or internet/cloud access, e.g. router reboot)?

Overall that’s probably a better question for Josh, but as far as the changes I made, what I assume would happen is that the attempt to connect locally will fail, it will attempt to use the cloud, which should work again once cloud access is restored. All the devices would continue using the cloud until the next HA restart.

**Comment by tggman** [comment] 2022-01-22 13:55
So far, all my bulbs are still functioning BUT I also don't have any ```cloud: true``` attributes. So this change remains untested on my HA server as of today -- proving once again, that intermittent problems never occur when you want them to. 

I'll keep watching ...

**Comment by tggman** [comment] 2022-01-24 15:08
Day 4:
Still **NO** bulb issues or ```cloud: true``` attributes. I'll keep monitoring.

**Comment by InstigatorX** [comment] 2022-01-24 19:45
@brg468 Dropped your wyzeapy in config and updated light.py. I've got a bulb flagged as Cloud: true, but it's still uncontrollable.

**Comment by brg468** [comment] 2022-01-24 19:47
> @brg468 Dropped your wyzeapy in config and updated light.py. I've got a bulb flagged as Cloud: true, but it's still uncontrollable.

Intersting... anything in the logs? And I assume its till controllable from the Wyze app?

**Comment by InstigatorX** [comment] 2022-01-24 19:58
Yes, controllable by the wyze app. Here's the log entry...

Logger: wyzeapy.services.base_service
Source: wyzeapy/services/base_service.py:613 
First occurred: 2:38:44 PM (1 occurrences) 
Last logged: 2:38:44 PM

Failed to connect to bulb 7C78B214131E, reverting to cloud.

**Comment by brg468** [comment] 2022-01-24 20:23
> EDT3: Got one of them to go true and changing to "_run_action_list" made it work.

Nice catch! It should be `_run_action_list` for the color bulbs. I swear I tested it and it worked, but I don't have bulbs, only the lightstrip so maybe that's why. 

Thanks for testing this out, I'll update and get a PR submitted

**Comment by InstigatorX** [comment] 2022-01-24 20:31
@brg468 Sweet. Happy to help.

**Comment by tggman** [comment] 2022-01-26 17:50
I updated to HassOS 7.2, rebooted and lo and behold, 1 of my 8 color bulbs reverted to ```Cloud: true```. But just like @InstigatorX it too was uncontrollable - which I assume was expected since I'm still using the original release of the ```wyzeapy``` and ```light.py``` (without the ```_run_action_list``` fix).

```Logger: wyzeapy.services.base_service
Source: wyzeapy/services/base_service.py:610
First occurred: 11:27:32 AM (1 occurrences)
Last logged: 11:27:32 AM

Failed to connect to bulb 7C78B2189DBA, reverting to cloud.
```
and

```2022-01-26 11:27:32 WARNING (MainThread) [wyzeapy.services.base_service] Failed to connect to bulb 7C78B2189DBA, reverting to cloud.```

So clearly rebooting HAC triggers the problem - but can't say why.

**Comment by brg468** [comment] 2022-01-26 17:58
> I updated to HassOS 7.2, rebooted and lo and behold, 1 of my 8 color bulbs reverted to `Cloud: true`. But just like @InstigatorX it too was uncontrollable - which I assume was expected since I'm still using the original release of the `wyzeapy` and `light.py` (without the `_run_action_list` fix).
> 
> ```
> Source: wyzeapy/services/base_service.py:610
> First occurred: 11:27:32 AM (1 occurrences)
> Last logged: 11:27:32 AM
> 
> Failed to connect to bulb 7C78B2189DBA, reverting to cloud.
> ```
> 
> and
> 
> `2022-01-26 11:27:32 WARNING (MainThread) [wyzeapy.services.base_service] Failed to connect to bulb 7C78B2189DBA, reverting to cloud.`
> 
> So clearly rebooting HAC triggers the problem - but can't say why.

Yeah that is expected with the version you have. You can redownload from my branch or the master branch of `wyzeapy`, 

I'm not sure if there's an updated version on HACS yet. No need to replace `light.py`, nothing changed there.

**Comment by tggman** [comment] 2022-01-27 00:06
I just installed the ```ha-wyzeapi``` v0.1.5-alpha.0 via HACS. Apparently ```light.py``` was not updated along with ```wyzeapy``` since none of my color bulbs have the ```cloud:``` attribute. Assuming this was not an oversight, may I suggest the final/next release contain the version of ```light.py``` that exposes the ```cloud:``` attribute.

**Comment by brg468** [comment] 2022-01-27 00:12
> I just installed the `ha-wyzeapi` v0.1.5-alpha.0 via HACS. Apparently `light.py` was not updated along with `wyzeapy` since none of my color bulbs have the `cloud:` attribute. Assuming this was not an oversight, may I suggest the final/next release contain the version of `light.py` that exposes the `cloud:` attribute.

You're right, its not an oversight. 

The cloud attribute should be in the next release. I think Josh made this a pre-release to ensure everything was still working correctly on the backend.

**Comment by tggman** [comment] 2022-02-04 14:46
been using this for almost 2 weeks now and the reliability is good!  are we releasing this code?

**Comment by JoshuaMulliken** [comment] 2022-02-04 21:39
@tggman I am incorporating a couple other changes in a new pre-release and if everything is good for a few more days I will make it stable.

**Comment by tggman** [comment] 2022-02-08 12:46
@JoshuaMulliken I've been running the latest code associated with issue #310 for that past few days so I still haven't had a chance to evaluate this pre-release (ha-wyzapi 0.1.5-alpha.1). 

Would it be possible to merge @brg468's code from issue #310  into your pre-release so I can start testing all the latest changes simultaneously? Again, I am not familiar with the merge and/or the release process so if I'm asking for something that doesn't make sense, I can evaluate the ha-wyzapi 0.1.5-alpha.1 separately.

**Comment by JoshuaMulliken** [comment] 2022-02-08 14:15
@tggman Yeah it is totally possible! @brg468 just needs to submit a PR with his changes, I will do the manual review, and then merge and push a new release.

**Comment by yoinx** [comment] 2022-02-09 21:01
> I am really getting sick of Wyze on so many fronts. I have a ton of LIFX lights which cost 3x more but have an open API and work flawlessly. Getting real close to biting the bullet and spending a bunch of money on LIFX. Anybody interested in 8 Wyze color bulbs? LOL

I'm in the same boat. My wife loves wyze's products, but isn't very tech savvy. I personally couldn't hate their products more. Even simple stuff, like getting a new DHCP address fails half the time. I spent the last week or two setting up a new cluster for my self hosted stuff, which kept taking my DHCP server up and down. Literally every device in my house, except the wyze products, couldn't care less... They'd grab a new address and keep steaming along.

Wyze's products on the other hand needed multiple power cycles, and being readded to the app repeatedly to get them working again. 

Though, I guess Wyze isn't to blame with DHCP being such a new protocol and all /sarcasm

Then there's the fact that for the first few years the company was churning out cameras, they were using self signed images for the firmware (which is why things like wyzehacks worked). I don't know if they stopped, or if something else broke wyzehacks ... But it definitely raises concerns.

**Comment by JoshuaMulliken** [comment] 2022-02-16 15:59
@tggman all the code submitted in the recent PRs is now in a stable release! Closing this issue.

**Closed by JoshuaMulliken** 2022-02-16 15:59 UTC
Labels: bug
