### ISSUE TITLE
Fails with Home assistant 2023.3 beta

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#462] opened 2023-02-23 01:40 UTC
**Describe the bug**
Won't load integration
**To Reproduce**

**Expected behavior**

**System configuration**
System: Home assistant os on odroid (home assistant blue)
HA Version: 2023.3 beta
WyzeApi Version: Newest beta and version .17

**home-assistant.log**
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 7:34:47 PM (1 occurrences)
Last logged: 7:34:47 PM

Setup failed for custom integration wyzeapi: Requirements for wyzeapi not found: ['wyzeapy==0.5.18'].

For additional information see the readme: https://github.com/JoshuaMulliken/ha-wyzeapi#reporting-an-issue
-->

```
Logger: homeassistant.setup
Source: setup.py:205
First occurred: 7:34:47 PM (1 occurrences)
Last logged: 7:34:47 PM

Setup failed for custom integration wyzeapi: Requirements for wyzeapi not found: ['wyzeapy==0.5.18'].

**Comment by jscherry** [comment] 2023-02-23 01:48
I even tried to uninstall, removed from hacs, redownloaded, rebooted, and reinstall but it says this when trying to install
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by chrisvball** [comment] 2023-02-23 01:55
same here.  I can post error, but identical.

**Comment by jbrown9100** [comment] 2023-02-23 03:40
Same for me.

**Comment by JoeSchubert** [comment] 2023-02-23 11:35
Is this still a problem?

The error is saying that it can't find that version of the wyzeapy library, which *should* have been pulled from pypi when you installed/upgraded. 

You can see that it's available here: https://pypi.org/project/wyzeapy/ with that version number... So I would venture a guess that this was an issue with pypi not serving it for some limited period of time.

**Comment by jscherry** [comment] 2023-02-23 13:25
How do we fix this?

**Comment by CenterInYou** [comment] 2023-02-23 14:53
@jscherry an update was just pushed out if you have it enabled to see beta versions but doesn't seem to have fixed it :(

**Comment by jscherry** [comment] 2023-02-23 19:51
I've tried the beta's and regular version. Neither work? Does anyone know how we can fix this until it's corrected in the integration?

**Comment by chrisvball** [comment] 2023-02-24 00:53
@jscherry  I rolled back HA 2023.3 beta back to the prod version 2023.2.5 and 1.17 with Wyze HACS.  And everything loaded.
For "fun" I took a backup of the VM and joined the beta and then it goes back to the original issue.  So restored it and back to working.  If I didn't have ~25 Wyze lights and ~20 cams I would just get away from the Wyze ecosystem, I just have so much, but nothing new..  I now just buy Zigbee or anything that isn't WiFi only, even my tuya lights are solid.  But honestly if I did it all over I would have just Hue lights, the 20 or so that i have running z2m work flawlessly.  Such a superior product, but 3x as much..  
I see HA as a way not to be limited by the cloud/internet i just didn't know about it soon enough..

**Comment by jscherry** [comment] 2023-02-24 02:23
@chrisvball I'm now restoring the backup also. I just hope someone can fix this issue before 3/1/23 when the regular 2023.3 version gets released. I've been using this integration since it was released and think it's great.

**Comment by chrisvball** [comment] 2023-02-24 02:32
My frustration lies with WYZE.  I understand they are in the money making business, but they should give you some local access if you have the product licensed.  It would be a win win with everyone.  I have the unlimited that gives me all the cloud features, but I don't use it, I did it to support their business model.  Hoping one day they could give us the rtsp firmware back and at least let a yearly subscriber go local.  
Good luck!

**Comment by brg468** [comment] 2023-02-24 16:58
I think the issue is [here](https://github.com/home-assistant/core/blame/c4e6088eff886e88a646b53a6a6e64c16f15440e/homeassistant/package_constraints.txt#L78). There was an update to the HA package constraints that no longer allows the wyzeapy requirements to be met.


@JoshuaMulliken or @JoeSchubert can you see what can be done to update or remove this requirement? HA is now requiring `faust-cchardet>=2.1.18`

**Comment by JoeSchubert** [comment] 2023-02-24 22:11
> I think the issue is [here](https://github.com/home-assistant/core/blame/c4e6088eff886e88a646b53a6a6e64c16f15440e/homeassistant/package_constraints.txt#L78). There was an update to the HA package constraints that no longer allows the wyzeapy requirements to be met. These are our requirements:
> 
> ```
> install_requires = \
> ['aiodns>=3.0.0,<4.0.0',
>  'aiohttp>=3.7,<4.0',
>  'cchardet>=2.1.7,<3.0.0',
>  'pycryptodome>=3.12.0,<4.0.0']
> ```
> 
> @JoshuaMulliken or @JoeSchubert can you see what can be done to update or remove this requirement? HA is now requiring `faust-cchardet>=2.1.18`

I'd be willing to bet it's a 1for1 swap based on the way that they're commit blocks that one and says that it's been replaced with faust-cchardet>=2.1.18

**Comment by jscherry** [comment] 2023-02-27 00:08
I've been looking through the cose trying to find where 'cchardet>=2.1.7,<3.0.0', is in hopes to edit it to faust-cchardet>=2.1.18 to see if that would fix the problem. Can someone please tell me where to find this piece of code so I can try it? The regular home assistant 2023.3 will be released this coming Wednesday and I'd like to be able to upgrade. Thanks, Jeff.

**Comment by brg468** [comment] 2023-02-27 00:18
That won’t work, it’s part of the wyzeapy library that’s published to PyPi. The best you could try is find the `package-constraints.txt` file in HA and comment out the line that blocks cchardet, which I linked to in the comment above. It does fix the issue, but the wyzeapy requirements need to be updated to correctly fix it.

**Comment by dnestico** [comment] 2023-03-01 20:45
Happening on full release too

**Comment by brg468** [comment] 2023-03-01 20:50
This probably goes without saying but don’t upgrade to 2023.3 until the fix is merged.

**Comment by tm24fan8** [comment] 2023-03-01 21:59
Wish I had seen this before updating. Thankfully I only have 2 Wyze lights...bad news is, they're the ones by my wife's desk. I'm gonna have some splainin to do LOL

**Comment by brg468** [comment] 2023-03-01 22:08
Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this:
```
  "requirements": [
    "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
  ],
```

**Comment by jdeath** [comment] 2023-03-01 23:03
> git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19

Thanks. That worked. I first tried just removing the version number and it didn't work!

**Comment by wildoracle** [comment] 2023-03-01 23:40
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

I tried this but got the following error:

```
Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 3:03:32 PM (15 occurrences)
Last logged: 3:29:49 PM

Unable to install package wyzeapy==0.5.16: ERROR: Cannot install wyzeapy==0.5.16 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip
```

**Comment by brg468** [comment] 2023-03-01 23:44
That’s the original error. Double check your manifest.json file that it’s exactly as above.

**Comment by CenterInYou** [comment] 2023-03-01 23:45
Thanks so much @brg468  !!!

**Comment by azsparks** [comment] 2023-03-02 00:01
Thanks @brg468 The manifest.json edit worked perfectly!

**Comment by brg468** [comment] 2023-03-02 01:38
Glad it worked everyone!  Hopefully have the official fix out soon.

**Comment by wildoracle** [comment] 2023-03-02 01:48
> That’s the original error. Double check your manifest.json file that it’s exactly as above.

I must not understand, but I'll wait for the official fix. Here's the entire contents of my manifest.json file including the edit you posted:
 
`{
  "domain": "wyzeapi",
  "version": "0.1.18b1",
  "name": "Wyze",
  "config_flow": true,
  "iot_class": "cloud_polling",
  "documentation": "https://github.com/JoshuaMulliken/ha-wyzeapi#readme",
  "issue_tracker": "https://github.com/JoshuaMulliken/ha-wyzeapi/issues",
  "requirements": [
    "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
  ],
  "codeowners": [
    "@JoshuaMulliken"
  ]
}
`

**Comment by brg468** [comment] 2023-03-02 02:02
> > That’s the original error. Double check your manifest.json file that it’s exactly as above.
> 
> I must not understand, but I'll wait for the official fix. Here's the entire contents of my manifest.json file including the edit you posted:
> 
> ```
> {
>   "domain": "wyzeapi",
>   "version": "0.1.18b1",
>   "name": "Wyze",
>   "config_flow": true,
>   "iot_class": "cloud_polling",
>   "documentation": "https://github.com/JoshuaMulliken/ha-wyzeapi#readme",
>   "issue_tracker": "https://github.com/JoshuaMulliken/ha-wyzeapi/issues",
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
>   "codeowners": [
>     "@JoshuaMulliken"
>   ]
> }
> ```

Hmm based on the error you posted, something seems off. It seems like it’s trying to install a wyzeapy from a few versions ago. You don’t have a wyzeapy folder in your config folder do you?

**Comment by scottjl** [comment] 2023-03-02 03:01
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

just changed out the one line, rebooted my yellow, wyze is working again. didn't have to re-install or change any configs, thankfully.

**Comment by bfish2** [comment] 2023-03-02 03:29
I had deleted and reinstalled the integration before searching and finding this fix.

I tried the fix, and was then able to enter my credentials.  Upon completion, the integration said successfully reauthenticated, but I still don't see the integration in my list of integrations, as I had previously.

**Comment by jason1980p** [comment] 2023-03-02 03:47
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

Thank you! Thank you! Thank you!!! This worked!

**Comment by wildoracle** [comment] 2023-03-02 06:54
> > > That’s the original error. Double check your manifest.json file that it’s exactly as above.
> > 
> > 
> > I must not understand, but I'll wait for the official fix. Here's the entire contents of my manifest.json file including the edit you posted:
> > ```
> > {
> >   "domain": "wyzeapi",
> >   "version": "0.1.18b1",
> >   "name": "Wyze",
> >   "config_flow": true,
> >   "iot_class": "cloud_polling",
> >   "documentation": "https://github.com/JoshuaMulliken/ha-wyzeapi#readme",
> >   "issue_tracker": "https://github.com/JoshuaMulliken/ha-wyzeapi/issues",
> >   "requirements": [
> >     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
> >   ],
> >   "codeowners": [
> >     "@JoshuaMulliken"
> >   ]
> > }
> > ```
> 
> Hmm based on the error you posted, something seems off. It seems like it’s trying to install a wyzeapy from a few versions ago. You don’t have a wyzeapy folder in your config folder do you?

No, I have a wyze_config.ini file in the config folder though...

**Comment by Cl3tus** [comment] 2023-03-02 13:23
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

This is exactly the comment that helped me out getting it to work again. Thanks!

**Comment by wildoracle** [comment] 2023-03-02 17:00
> > > That’s the original error. Double check your manifest.json file that it’s exactly as above.
> > 
> > 
> > I must not understand, but I'll wait for the official fix. Here's the entire contents of my manifest.json file including the edit you posted:
> > ```
> > {
> >   "domain": "wyzeapi",
> >   "version": "0.1.18b1",
> >   "name": "Wyze",
> >   "config_flow": true,
> >   "iot_class": "cloud_polling",
> >   "documentation": "https://github.com/JoshuaMulliken/ha-wyzeapi#readme",
> >   "issue_tracker": "https://github.com/JoshuaMulliken/ha-wyzeapi/issues",
> >   "requirements": [
> >     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
> >   ],
> >   "codeowners": [
> >     "@JoshuaMulliken"
> >   ]
> > }
> > ```
> 
> Hmm based on the error you posted, something seems off. It seems like it’s trying to install a wyzeapy from a few versions ago. You don’t have a wyzeapy folder in your config folder do you?

I seem to have a bigger issue than Wyze - I can no longer restart Home Assistant?!
I don't know how to fix this but I submitted an issue to Home Assistant Core about it... do you have any quick fix for this? 
`
The system cannot restart because the configuration is not valid: Integration error: config_editor - Integration 'config_editor' not found.`

**Comment by bbushelle** [comment] 2023-03-02 18:00
Made the change posted by brg468 to manifest.json and did a full reboot but am getting the following error: 

> Failed to call service light/turn_on. BulbService.turn_on() missing 1 required position argument: 'local_control'

Still trying to troubleshoot/resolve but wondering if anyone else encountered this as well?

**Comment by bbushelle** [comment] 2023-03-03 00:47
@brg468 - yes when toggling on/off

"version": "2021.11.1"

I'm wondering if that is my problem since I'm seeing "version": "0.1.18b1" as current now.  

HACS isn't telling me there is an update available so will try manually doing that

**Comment by brg468** [comment] 2023-03-03 00:52
2021.11.1 is the Wyze version?  That’s really old! 😛 (over 2 years based on the numbering) I’m guessing your Wyze integration is missing local control for bulbs which is what the newer dependency is looking for.

**Comment by run1fast** [comment] 2023-03-03 01:00
I'm on that same Wyze version "version": "2021.11.1". Its always worked OK for me, until this recent HA update. So I did the update brg468 recommended which fixed the integration. But now getting the same error as bbushelle.
Just pulled the "version": "0.1.18b1", updated, restarted HA.
The error message is gone and I can now control my wyze lights. At least they work, but there is a LONG delay. From when I turn on a bulb in HA, it takes nearly 8-10 secs for the bulb to turn on. When I try to turn it off, I click the slider in HA, 2 secs later, the slider automatically goes back to on. Then I try it again, wait 8sec and the bulb turns off.

**Comment by bbushelle** [comment] 2023-03-03 01:04
@brg468 lol yup.  I guess when things don't yell at me to be updated they get forgotten as long as they're still working.

Lights are working again and no delay like @run1fast is experiencing.  I upgraded my version to 0.1.17

**Comment by JAudi23** [comment] 2023-03-03 03:08
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

This fixed it for me as well.

**Comment by christophermichaelshaw** [comment] 2023-03-03 04:32
@JAudi23 Thank you for the clear instructions for a fix! 

@JoshuaMulliken  Any idea when this PR will be merged/approved?

**Comment by gmitchell3** [comment] 2023-03-03 13:13
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

@brg468 Thank you so much for this easy to follow and apply fix. It worked great.  Much appreciated.

**Comment by PaPaTheGMan** [comment] 2023-03-03 13:44
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

Thanks - this worked for me.  Very much appreciated, I have multiple camera turn-on/off automations based on presence and this brings everything back online!

**Comment by 1PlusN** [comment] 2023-03-03 17:28
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

works like a charm!

**Comment by dorgan** [comment] 2023-03-03 19:00
wish i had known about this before upgrading....Trying to update manifest.json now but it seems to not be working....

**Comment by brg468** [comment] 2023-03-03 19:22
@dorgan I'm happy to help but you'll have to be more specific than 'not working'

**Comment by dorgan** [comment] 2023-03-03 21:53
@brg468 a full restart and I am good now. Thanks!

**Comment by bl232** [comment] 2023-03-03 22:08
> Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> 
> ```
>   "requirements": [
>     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
>   ],
> ```
> 
> You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.

I encountered this issue (the fix worked for me) and just wanted to say thanks for all the time and effort put into fixing these kinds of things. The reading lights in my bedroom are now working again :)

**Comment by jayste4** [comment] 2023-03-03 23:02
> > Anyone that already upgraded, you can try editing your` manifest.json` file found in config->custom_components->wyzeapi and replacing the current requirements block with this and restart:
> > ```
> >   "requirements": [
> >     "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"
> >   ],
> > ```
 
> > You may have to delete and reload the integration but I don’t think so. When a new version is available in HACS it will overwrite this. Obviously do this at your own risk, worst case redownload the integration from HACS.
> 
> I encountered this issue (the fix worked for me) and just wanted to say thanks for all the time and effort put into fixing these kinds of things. The reading lights in my bedroom are now working again :)

I modified the manifest.json then updated to 2023.3.1 and the Wyze intergration is working.

**Closed** 2023-03-05 19:08 UTC
Labels: bug

**Comment by RebbePod** [comment] 2023-03-06 18:47
I'm having trouble uninstalling, any ideas?

**Comment by droptopgokart** [comment] 2023-03-08 01:38
> @brg468 lol yup.  I guess when things don't yell at me to be updated they get forgotten as long as they're still working.
> 
> Lights are working again and no delay like @run1fast is experiencing.  I upgraded my version to 0.1.17

How do you upgrade without the HACS prompt?  I'm getting the same error.

**Comment by brg468** [comment] 2023-03-08 02:22
> > @brg468 lol yup.  I guess when things don't yell at me to be updated they get forgotten as long as they're still working.
> > Lights are working again and no delay like @run1fast is experiencing.  I upgraded my version to 0.1.17
> 
> How do you upgrade without the HACS prompt? I'm getting the same error.

Find the integration in HACS->three dots upper right->redownload button.

**Comment by realsimon** [comment] 2024-03-05 16:46
> "git+https://github.com/brg468/wyzeapy.git@update-deps#wyzeapy==0.5.19"

I changed this, and now integration said that my API key expired (it didn't) and asking me to re-enter login info.
I created a new API key, but getting "Unknown error occurred" with the following debug info:

2024-03-05 11:13:56.998 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wyzeapi/config_flow.py", line 61, in async_step_user
    await self.client.login(
          ^^^^^^^^^^^^^^^^^^
TypeError: Wyzeapy.login() takes from 3 to 4 positional arguments but 5 were given
