### ISSUE TITLE
New V2 sensors

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#148] opened 2021-04-29 03:43 UTC
I'm still running an older version that still works with the sensors. I just set up the new home monitoring system and all the new V2 sensors are working perfectly in home assistant. Door contacts and motions. Maybe you shouldn't completely trash the idea of keeping sensors in your api version. All the old sensors and newer sensors are working. This is awesome. The alarm keypad and new sensor hub don't show up but all the new sensors do.

**Comment by JoshuaMulliken** [comment] 2021-04-29 13:13
Duplicate of https://github.com/JoshuaMulliken/ha-wyzeapi/issues/140

**Closed by JoshuaMulliken** 2021-04-29 13:13 UTC
