### ISSUE TITLE
Switches stop working and/or fail to update status (again)

### ISSUE THREAD

**Issue by b0rrasca** [JoshuaMulliken/ha-wyzeapi#354] opened 2022-02-24 15:14 UTC
**Describe the bug**
Switches stop working and/or fail to update status (e.g. shows light on when they are not and viceversa)

**To Reproduce**

Seems to happen at random

**Expected behavior**
Status should update, and toggles should work

**System configuration**
System: Docker
HA Version: 2022.2.9
WyzeApi Version: 0.1.7

**home-assistant.log**

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/wyzeapi/switch.py:173
Integration: Wyze Home Assistant Integration (documentation, issues)
First occurred: 10:09:26 AM (2 occurrences)
Last logged: 10:09:26 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 173, in async_turn_on
    await self._service.turn_on(self._device)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/switch_service.py", line 43, in turn_on
    await self._set_property(switch, PropertyIDs.ON.value, "1")
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 338, in _set_property
    await self._auth_lib.refresh_if_should()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 178, in refresh_if_should
    await self.refresh()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 200, in refresh
    response_json = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1098, in json
    await self.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Comment by b0rrasca** [comment] 2022-02-24 18:28
Another error log, in case it is helpful. 

```This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/wyzeapi/switch.py:173
Integration: Wyze Home Assistant Integration (documentation, issues)
First occurred: 7:59:41 AM (4 occurrences)
Last logged: 8:24:46 AM

Error executing service: <ServiceCall switch.turn_on (c:6061358d35e706b1a380ff8830a80526): entity_id=['switch.basement_1']>
Error executing service: <ServiceCall switch.turn_on (c:26557a302eee1de896f4cbbea4ed7e14): entity_id=['switch.basement_2']>
Error executing service: <ServiceCall switch.turn_on (c:12caf3e39644f52043b63305330c3094): entity_id=['switch.basement_1', 'switch.basement_2']>
Error executing service: <ServiceCall switch.turn_on (c:67bad6fd21f850f28cc0b583839f89c0): entity_id=['switch.basement_1', 'switch.basement_2']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1648, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/wyzeapi/token_manager.py", line 45, in inner_function
    await func(*args, **kwargs)
  File "/config/custom_components/wyzeapi/switch.py", line 173, in async_turn_on
    await self._service.turn_on(self._device)
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/switch_service.py", line 43, in turn_on
    await self._set_property(switch, PropertyIDs.ON.value, "1")
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/services/base_service.py", line 338, in _set_property
    await self._auth_lib.refresh_if_should()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 178, in refresh_if_should
    await self.refresh()
  File "/usr/local/lib/python3.9/site-packages/wyzeapy/wyze_auth_lib.py", line 200, in refresh
    response_json = await response.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1098, in json
    await self.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1036, in read
    self._body = await self.content.read()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by JoshuaMulliken** [comment] 2022-02-24 19:45
These are network read errors. I am not sure what we can do to ensure that your network connection is solid between you and the API.

**Comment by caseyjames22** [comment] 2022-02-25 09:48
I have of these "switches" (They're plugs, wish the switch was integrated.) and have been having this problem for months, if not a good year now. Even in a room that never loses network access, they'll go offline and need to be reinstalled.
Sucks, but Wyze dropped the ball on these things.

**Comment by yoinx** [comment] 2022-02-25 17:12
Yeah. It's a known problem. They put out a beta firmware recently that was supposed to fix them. The comments are all "still broke".

It isn't an issue with ha or the integration. These switches just randomly decide that they don't have an ip address, then might randomly decide that they do... Or that they need to be re-paired into the app.

I've finally convinced my wife to stop buying wyze trash. So I'm just stuck with what I have until those devices break (so far longevity doesn't seem that great) until we move to a better brand (still looking for one that fits what I want).

Wyze used to be decent, but they started trying to release far too many devices and their quality control is garbage now... On the devices and the firmware releases.

**Comment by caseyjames22** [comment] 2022-02-25 20:08
ya know, I was going to argue this.... but then i read it all... and you're not wrong... what started great and cheap has turned into just cheap and massively over produced. I still havethe old school products, and besides the plugs, and this vacuum, work like fuckin champs... I think in the end, the real problem is trying to fix something aint broke. Ya know?

**Comment by yoinx** [comment] 2022-02-25 21:07
Right. I mean I think hardware wise, the products aren't terrible. Though, I've had a few issues in the ~2 years I've owned these products. They've all been warrantied so far. However, one of those was from a firmware update bricking the device (which already had pretty unforgivable problems in the firmware prior to that, which took quite a few months to fix).

The issue is that they, as far as I can tell, have zero quality control beyond the users who opt into the beta. The problem with that is that most people are just going to roll back to what worked if a beta breaks things. You're probably only going to get feedback from like 5 users out of every 100 that use a beta.... If you're lucky. From the things I've seen being pushed out, I would be shocked to hear that they actually do anything besides making sure that a firmware successfully flashes before rolling it out as a beta.

Add to that, they have worse turnaround on fixing critical bugs than volunteer based / open source projects. It was like 6 months between when people started reporting the Outdoor Cam Base station taking down their home networks (since it l basically introduced a rouge dhcp server on the lan).... A problem that never should have made it through testing... And should have been as simple to fix as restricting the dhcp server to the wifi interface. Meanwhile, people were reporting having their ISPs sending out support techs (and likely incurring costs as a result). 

Fast forward to this plug thing. Barring simply handling a DHCP lease correctly, as that would be the first option... It could be as simple of a fix as just introducing a watchdog that requests a new IP if it can't access the router ip. Then, after x attempts, fall back to pairing mode. Instead, they fallback to pairing mode immediately from the looks of it. But instead, here we are with at least a month or two now that this has been an issue... I don't know about you, but I've had my plugs for at least 6 months or more. It wasn't a problem originally.... So they obviously broke something during a firmware update. Why are they not just doing a git bisect on that firmware since it started being a problem to figure out what change broke it? No idea. However, the fact that it's a bug that effectively renders the product they sold is nearly useless, due to their crap quality control, you would think they'd have it figured out pretty quickly.

**Comment by JoshuaMulliken** [comment] 2022-04-03 17:27
Don’t think there is anything this integration can do to fix this issue. I am closing this for now

**Closed by JoshuaMulliken** 2022-04-03 17:27 UTC
Labels: bug
